# Generated by Django 3.0.10 on 2020-09-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifilis', '0002_auto_20200923_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='medicamento',
            unique_together={('nome', 'solucao', 'metodo')},
        ),
    ]
