# Generated by Django 3.0.10 on 2020-09-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifilis', '0006_auto_20200924_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='situacao',
            field=models.CharField(choices=[('Já teve a doença', 'teve'), ('Está atualmente com a doença', 'tem'), ('Não tem a doença', 'nao tem')], default='', max_length=255, verbose_name='Situação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='tipo_de_relacionamento',
            field=models.CharField(choices=[('Pai', 'pai'), ('Mãe', 'mae')], max_length=255),
        ),
    ]
