# Generated by Django 3.0.10 on 2020-09-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200916_1028'),
        ('sifilis', '0007_auto_20200924_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedente',
            name='cid',
        ),
        migrations.AddField(
            model_name='antecedente',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sifilis.CID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='situacao',
            field=models.CharField(choices=[('teve', 'Já teve a doença'), ('tem', 'Está atualmente com a doença'), ('nao_tem', 'Não tem a doença')], max_length=255, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='planoterapeuticopaciente',
            name='situacao',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso')], default='em_andamento', max_length=255, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sifilis_relacionamento_set', to='base.PessoaFisica'),
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='tipo_de_relacionamento',
            field=models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe')], max_length=255),
        ),
    ]
