# Generated by Django 3.0.7 on 2020-06-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloboletimepidemiologico',
            options={'verbose_name': 'modelo de boletim epidemiológico', 'verbose_name_plural': 'modelos de boletim epidemiológico'},
        ),
    ]
