# Generated by Django 3.0.7 on 2020-07-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_auto_20200630_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeloBoletimEpidemiologico',
            new_name='ModeloPainel',
        ),
        migrations.AlterModelOptions(
            name='modelopainel',
            options={'verbose_name': 'modelo de painél', 'verbose_name_plural': 'modelos de painél'},
        ),
    ]
