# Generated by Django 3.0.7 on 2020-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20200702_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelopainel',
            options={'verbose_name': 'modelo de painel', 'verbose_name_plural': 'modelos de painel'},
        ),
        migrations.AddField(
            model_name='modelopainel',
            name='tipo',
            field=models.CharField(choices=[('boletim', 'Boletim'), ('sala_situacao', 'Sala de situação'), ('publico', 'Painél público'), ('outro', 'Outro')], default='outro', max_length=100),
        ),
    ]
