# Generated by Django 3.0.7 on 2020-07-02 15:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_boletim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletim',
            options={'verbose_name_plural': 'boletins'},
        ),
        migrations.AddField(
            model_name='boletim',
            name='criado_em',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletim',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boletim',
            name='dados',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
