# Generated by Django 3.0.7 on 2020-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0006_auto_20200702_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
