# Generated by Django 3.0.7 on 2020-07-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0009_auto_20200702_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boletim',
        ),
    ]
