# Generated by Django 3.0.7 on 2020-07-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0010_delete_boletim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloaplicacao',
            options={'verbose_name': 'modelo aplicado', 'verbose_name_plural': 'modelos aplicados'},
        ),
        migrations.RemoveField(
            model_name='modeloaplicacao',
            name='data',
        ),
    ]
