# Generated by Django 3.0.7 on 2020-08-10 01:58
from django.core.management import call_command
from django.db import migrations


def importa_fixtures_painel_publico(apps, schema_editor):
    call_command('loaddata', 'indicadores/fixtures/modelo_painel_publico_final.json')


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0011_auto_20200703_0020'),
    ]

    operations = [
        migrations.RunPython(importa_fixtures_painel_publico)
    ]
