# Generated by Django 3.0.6 on 2020-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_auto_20200601_1328'),
        ('base', '0003_pacienteinternacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteInternacao',
        ),
    ]
