# Generated by Django 3.0.7 on 2020-06-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_associacaonomeestabelecimentosaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilatencaobasica',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilatencaoespecializada',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfildistrito',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilvigilancia',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
    ]
