# Generated by Django 3.0.7 on 2020-06-04 01:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_associacaonomeestabelecimentosaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cpf', models.CharField(db_index=True, max_length=11, null=True, verbose_name='CPF')),
                ('cns', models.CharField(db_index=True, max_length=15, null=True, verbose_name='CNS')),
            ],
        ),
    ]
