# Generated by Django 3.0.7 on 2020-06-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200603_2203'),
        ('base', '0006_pessoafisica'),
    ]

    operations = [
    ]
