# Generated by Django 3.0.7 on 2020-06-04 06:14

from django.db import migrations, models

from notificacoes.models import PacienteInternacao


# def excluir_todos_pacientes(a, b):
#     PacienteInternacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200603_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cns',
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        # migrations.RunPython(excluir_todos_pacientes)
    ]
