# Generated by Django 3.0.7 on 2020-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200604_0314'),
    ]

    operations = [
#         migrations.RunSQL(
#             '''
# update notificacoes_notificacao
# set pessoa_id = null;
# delete from base_pessoafisica;
#             '''
#         ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
