# Generated by Django 3.0.7 on 2020-06-04 15:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_associacaooperadorcnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaooperadorcnes',
            name='dados',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
