# Generated by Django 3.0.7 on 2020-06-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200605_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('e_gestor', 'É gestor')], 'verbose_name': 'usuário'},
        ),
        migrations.RemoveField(
            model_name='perfilatencaobasica',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='perfilatencaoespecializada',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='perfildistrito',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='perfilvigilancia',
            name='gestor',
        ),
    ]
