# Generated by Django 3.0.7 on 2020-06-05 03:08
from django.core.management import call_command
from django.db import migrations


def createcachetable(a,b):
    call_command('createcachetable', verbosity=3)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_associacaooperadorcnes_dados'),
    ]

    operations = [
        migrations.RunPython(createcachetable)
    ]
