# Generated by Django 3.0.7 on 2020-06-10 15:05

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200608_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
