# Generated by Django 3.0.7 on 2020-06-10 22:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200610_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='dados',
            new_name='dados_esusve',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='dados_monitoramento',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
