# Generated by Django 3.0.7 on 2020-06-14 22:38
import os

from django.conf import settings
from django.db import migrations

from base.management.commands.processar_arquivos_auxiliares import processar_estabelecimento_saude


def importar_estabelecimento_saude_cnes(a, b):
    path_dir_fixtures = os.path.join(settings.BASE_DIR, 'base/fixtures')
    filename = os.path.join(path_dir_fixtures, 'tb_estabelecimentos_rn.csv')
    processar_estabelecimento_saude(filename)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200610_1925'),
    ]

    operations = [
        migrations.RunPython(importar_estabelecimento_saude_cnes)
    ]
