# Generated by Django 3.0.7 on 2020-06-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200614_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Distrito'),
        ),
    ]
