# Generated by Django 3.0.7 on 2020-06-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_estabelecimentosaude_distrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associacaobairro',
            options={'verbose_name': 'associação de bairro', 'verbose_name_plural': 'associações de bairros'},
        ),
        migrations.AlterModelOptions(
            name='associacaonomeestabelecimentosaude',
            options={'verbose_name': 'associação de nome e estabelecimento de sáude', 'verbose_name_plural': 'associações de nomes de estabelecimentos de sáude'},
        ),
        migrations.AlterModelOptions(
            name='estabelecimentosaude',
            options={'verbose_name': 'estabelecimento de saúde', 'verbose_name_plural': 'estabelecimentos de saúde'},
        ),
        migrations.AlterModelOptions(
            name='habitacoesbairro',
            options={'verbose_name': 'habitação de bairro', 'verbose_name_plural': 'habitações de bairros'},
        ),
        migrations.AlterModelOptions(
            name='perfilatencaobasica',
            options={'verbose_name': 'perfil de atenção básica', 'verbose_name_plural': 'perfis de atenção básica'},
        ),
        migrations.AlterModelOptions(
            name='perfilatencaoespecializada',
            options={'verbose_name': 'perfil de atenção especializada', 'verbose_name_plural': 'perfis de atenção especializada'},
        ),
        migrations.AlterModelOptions(
            name='perfildistrito',
            options={'verbose_name': 'perfil de distrito', 'verbose_name_plural': 'perfis de distrito'},
        ),
        migrations.AlterModelOptions(
            name='perfilestabelecimentosaude',
            options={'verbose_name': 'perfil de estabelecimento de saúde', 'verbose_name_plural': 'perfis de estabelecimento de saúde'},
        ),
        migrations.AlterModelOptions(
            name='perfilvigilancia',
            options={'verbose_name': 'perfil de vigilância', 'verbose_name_plural': 'perfis de vigilância'},
        ),
        migrations.AddField(
            model_name='perfilestabelecimentosaude',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
