# Generated by Django 3.0.7 on 2020-06-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200617_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilatencaobasica',
            options={'verbose_name': 'Perfil Departamento de Atenção Básica', 'verbose_name_plural': 'Perfis Departamento de Atenção Básica'},
        ),
    ]
