# Generated by Django 3.0.7 on 2020-06-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200622_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='quant_populacao',
            field=models.PositiveIntegerField(default=0, verbose_name='População estimada'),
            preserve_default=False,
        ),
    ]
