# Generated by Django 3.0.7 on 2020-06-30 23:29

from django.db import migrations

from base.models import Municipio


def set_populacao_natal(a, b):
    Municipio.objects.filter(codigo_ibge='240810').update(quant_populacao=884122)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_municipio_quant_populacao'),
    ]

    operations = [
        migrations.RunPython(set_populacao_natal)
    ]
