# Generated by Django 3.0.7 on 2020-07-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200706_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadefederativa',
            name='sigla',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
