# Generated by Django 3.0.7 on 2020-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200729_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='quant_populacao',
            field=models.PositiveIntegerField(default=0, verbose_name='População estimada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distrito',
            name='quant_populacao',
            field=models.PositiveIntegerField(default=0, verbose_name='População estimada'),
            preserve_default=False,
        ),
    ]
