# Generated by Django 3.0.7 on 2020-08-04 19:31
import os
from django.conf import settings
from django.db import migrations
from base.management.commands.processar_arquivos_auxiliares import  processar_populacao

def corrigir_dados_bairros(apps, schema_editor):
    Distrito = apps.get_model('base', 'Distrito')
    Bairro = apps.get_model('base', 'Bairro')


    path_dir_fixtures = os.path.join(settings.BASE_DIR, 'base/fixtures')

    filename = os.path.join(path_dir_fixtures, 'distritos_populacoes.csv')
    processar_populacao(filename, Distrito)


    filename = os.path.join(path_dir_fixtures, 'bairros_populacoes.csv')
    processar_populacao(filename, Bairro)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200804_1617'),
    ]

    operations = [
        migrations.RunPython(corrigir_dados_bairros)
    ]