# Generated by Django 3.0.7 on 2020-08-24 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import newadmin.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20200821_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='celulares',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Celulares'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cep',
            field=newadmin.utils.CepModelField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão Sus'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='complemento',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='data_de_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Municipio'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nome',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informado'), ('I', 'Indefinido')], default='N', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='telefones',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefones'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
    ]
