# Generated by Django 3.0.7 on 2020-09-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_pessoafisica_nome_da_mae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='dados_esusve',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='dados_monitoramento',
        ),
    ]
