# Generated by Django 3.0.7 on 2020-09-02 21:21
import os
from django.conf import settings

from django.db import migrations

from base.management.commands.processar_arquivos_auxiliares import processar_ufs


def ajustar_dados_ufs(apps, schema_editor):
    path_dir_fixtures = os.path.join(settings.BASE_DIR, 'base/fixtures')
    filename = os.path.join(path_dir_fixtures, 'ufs.json')
    processar_ufs(filename)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200901_1003'),
    ]

    operations = [
        migrations.RunPython(ajustar_dados_ufs)
    ]
