# Generated by Django 3.0.10 on 2020-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20200902_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='raca',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena')], max_length=255, verbose_name='Raça'),
        ),
    ]
