# Generated by Django 3.0.6 on 2020-05-29 04:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImportacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('numero', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='número da notificação')),
                ('dados_esusve', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hash_dados_esusve', models.CharField(db_index=True, max_length=56, verbose_name='Hash dados esusve')),
                ('dados_esusve_atualizados_em', models.DateTimeField(null=True)),
                ('numero_gal', models.CharField(max_length=12, null=True, verbose_name='número do GAL')),
                ('ativa', models.BooleanField(default=True)),
                ('pendente', models.BooleanField(default=False)),
                ('dados_cep', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dados_cep_atualizados_em', models.DateTimeField(null=True)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Bairro')),
                ('estabelecimento_saude', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EstabelecimentoSaude')),
                ('notificacao_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.Notificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dados', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacoes.Notificacao', verbose_name='Notificação')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
