# Generated by Django 3.0.6 on 2020-05-29 08:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='dados_esusve_alterado',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
