# Generated by Django 3.0.6 on 2020-05-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_dados_esusve_alterado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='pendente',
        ),
    ]
