# Generated by Django 3.0.6 on 2020-06-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pacienteinternacao'),
        ('notificacoes', '0003_remove_notificacao_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='paciente_internado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.PacienteInternacao'),
        ),
    ]
