# Generated by Django 3.0.6 on 2020-06-01 16:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_notificacao_paciente_internado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteInternacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_identificacao', models.CharField(max_length=56, unique=True)),
                ('codigo_cnes', models.CharField(max_length=7, verbose_name='código CNES')),
                ('dados_censo_leitos', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_ultimo_processamento', models.DateTimeField(null=True)),
                ('tipo', models.CharField(choices=[['I', 'Internado'], ['M', 'Morto'], ['A', 'NÃO consta no PDF']], max_length=1, null=True)),
                ('dados_regularn', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dados_regularn_atualizados_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='paciente_internado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.PacienteInternacao'),
        ),
    ]
