# Generated by Django 3.0.7 on 2020-06-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0006_auto_20200602_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'permissions': [('pode_definir_notificacoes_principais', 'Pode definir notificações principais'), ('pode_associar_bairros', 'Pode associar bairros'), ('pode_importar_notificacoes', 'Pode importar notificações'), ('pode_importar_pacientes', 'Pode importar pacientes'), ('pode_associar_pacientes', 'Pode associar pacientes'), ('pode_ver_todas_as_notificacoes', 'Pode ver todas as notificações')]},
        ),
    ]
