# Generated by Django 3.0.7 on 2020-06-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pessoafisica'),
        ('notificacoes', '0007_auto_20200603_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.PessoaFisica'),
        ),
    ]
