# Generated by Django 3.0.7 on 2020-06-04 02:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0008_notificacao_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='dados_esusve_alterado',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
