# Generated by Django 3.0.7 on 2020-06-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0009_auto_20200603_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='pessoa',
        ),
    ]
