# Generated by Django 3.0.7 on 2020-06-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0013_auto_20200606_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'permissions': [('pode_definir_notificacoes_principais', 'Pode definir notificações principais'), ('pode_associar_bairros', 'Pode associar bairros'), ('pode_importar_notificacoes', 'Pode importar notificações'), ('pode_importar_pacientes', 'Pode importar pacientes'), ('pode_associar_pacientes', 'Pode associar pacientes'), ('pode_associar_operadores', 'Pode associar operadores'), ('pode_associar_estabelecimentos', 'Pode associar estabelecimentos'), ('pode_ver_todas_as_notificacoes', 'Pode ver todas as notificações'), ('pode_alterar_o_gal', 'Pode alterar o GAL')], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
    ]
