# Generated by Django 3.0.7 on 2020-06-08 00:21

from django.db import migrations

from notificacoes.models import Notificacao


def define_ceps_none(a, b):
    Notificacao.objects.filter(dados_cep={}).update(dados_cep=None)

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0014_auto_20200607_1429'),
    ]

    operations = [
        migrations.RunPython(define_ceps_none)
    ]
