# Generated by Django 3.0.7 on 2020-06-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200608_2353'),
        ('notificacoes', '0015_auto_20200607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.PessoaFisica'),
        ),
    ]
