# Generated by Django 3.0.7 on 2020-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0017_auto_20200610_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='tipo',
            field=models.CharField(choices=[['I', 'Internado'], ['M', 'Morto'], ['A', 'Liberado']], max_length=1, null=True),
        ),
    ]
