# Generated by Django 3.0.7 on 2020-06-10 23:22

from django.db import migrations

from notificacoes.models import Notificacao


def corrigi_dados_alterados_notificacao(a, b):
    for numero, dados_esusve_alterado in Notificacao.objects.filter(
            dados_esusve_alterado__has_key='operador_cnes').values_list('numero', 'dados_esusve_alterado'):
        if len(dados_esusve_alterado) > 1:
            dados_esusve_alterado.pop('operador_cnes')
            Notificacao.objects.filter(numero=numero).update(dados_esusve_alterado=dados_esusve_alterado)
        else:
            Notificacao.objects.filter(numero=numero).update(dados_esusve_alterado=None)


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0018_auto_20200610_1925'),
    ]

    operations = [
        migrations.RunPython(corrigi_dados_alterados_notificacao)
    ]
