# Generated by Django 3.0.7 on 2020-06-11 00:41

from django.db import migrations

from notificacoes.models import PacienteInternacao


def atualiza_dados (a, b):
    for p in PacienteInternacao.objects.exclude(dados_censo_leitos__has_key='data_de_liberacao'):
        p.dados_censo_leitos['data_de_liberacao'] = ''
        p.save(update_fields=['dados_censo_leitos'])

    for p in PacienteInternacao.objects.exclude(dados_censo_leitos__has_key='data_de_admissao'):
        p.dados_censo_leitos['data_de_admissao'] = ''
        p.save(update_fields=['dados_censo_leitos'])

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0019_auto_20200610_2022'),
    ]

    operations = [
        migrations.RunPython(atualiza_dados)
    ]
