# Generated by Django 3.0.7 on 2020-06-12 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0020_auto_20200610_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 22, 20, 35, 12873, tzinfo=utc), verbose_name='Data da Notificação'),
            preserve_default=False,
        ),
    ]
