# Generated by Django 3.0.7 on 2020-06-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0022_auto_20200614_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-data_de_investigacao']},
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data da Notificação'),
        ),
    ]
