# Generated by Django 3.0.7 on 2020-06-17 03:01

from django.db import migrations

from notificacoes.models import Notificacao


def desativar_notificacoes_nomes_null(a, b):
    Notificacao.objects.filter(dados_esusve__nome_completo=None).update(ativa=False)

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0023_auto_20200615_2354'),
    ]

    operations = [
        migrations.RunPython(desativar_notificacoes_nomes_null)
    ]
