# Generated by Django 3.0.7 on 2020-06-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0024_auto_20200617_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='tipo',
            field=models.CharField(choices=[['I', 'Internado'], ['O', 'Óbito'], ['A', 'Liberado']], max_length=1, null=True),
        ),
    ]
