# Generated by Django 3.0.7 on 2020-06-18 02:59

from django.db import migrations


def apagar_internacoes(apps, schema_editor):
    PacienteInternacao = apps.get_model('notificacoes', 'PacienteInternacao')
    PacienteInternacao.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0025_auto_20200617_2359'),
    ]

    operations = [
        migrations.RunPython(apagar_internacoes)
    ]
