# Generated by Django 3.0.7 on 2020-06-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0026_auto_20200617_2359'),
        ('notificacoes', '0025_auto_20200617_0131'),
    ]

    operations = [
    ]
