# Generated by Django 3.0.7 on 2020-06-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200617_1750'),
        ('notificacoes', '0027_merge_20200618_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteinternacao',
            name='codigo_cnes',
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='estabelecimento_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EstabelecimentoSaude'),
        ),
    ]
