# Generated by Django 3.0.7 on 2020-06-18 04:24

from django.db import migrations

from notificacoes.models import PacienteInternacao


def apagar_internacoes(a, b):
    PacienteInternacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0028_auto_20200618_0123'),
    ]

    operations = [
        migrations.RunPython(apagar_internacoes)
    ]
