# Generated by Django 3.0.7 on 2020-06-21 13:35
from django.core.cache import cache
from django.db import migrations

def delete_cacheprocessamentonotificacao_status(a, b):
    cache.delete('_cacheprocessamentonotificacao_status')

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0029_auto_20200618_0124'),
    ]

    operations = [
        migrations.RunPython(delete_cacheprocessamentonotificacao_status)
    ]
