# Generated by Django 3.0.7 on 2020-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0030_auto_20200621_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='coordendas_atualizadas_em',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
