# Generated by Django 3.0.7 on 2020-06-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200622_1115'),
        ('notificacoes', '0032_auto_20200621_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='estabelecimento_saude_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacaoreferencia_set', to='base.EstabelecimentoSaude', verbose_name='Estabelecimento de Saúde de referência'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='estabelecimento_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EstabelecimentoSaude', verbose_name='Estabelecimento de Saúde do cadastro'),
        ),
    ]
