# Generated by Django 3.0.7 on 2020-06-29 01:01

from django.db import migrations


def limpar_estabelecimento_saude_referencia(apps, schema_editor):
    apps.get_model('notificacoes', 'Notificacao').objects.update(estabelecimento_saude_referencia=None,
                                                                 coordenadas_atualizadas_em=None)


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0033_auto_20200625_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='coordendas_atualizadas_em',
            new_name='coordenadas_atualizadas_em',
        ),
        migrations.RunPython(limpar_estabelecimento_saude_referencia)
    ]
