# Generated by Django 3.0.7 on 2020-07-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200622_1115'),
        ('notificacoes', '0034_auto_20200628_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinternacao',
            name='endereco_bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Bairro'),
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='obito_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='sexo',
            field=models.CharField(blank=True, choices=[['M', 'M'], ['F', 'F']], max_length=1),
        ),
    ]
