# Generated by Django 3.0.7 on 2020-07-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200622_1115'),
        ('notificacoes', '0035_auto_20200630_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteinternacao',
            name='obito_verificado',
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='data_do_obito',
            field=models.DateField(null=True, verbose_name='Data do óbito'),
        ),
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='endereco_bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Bairro', verbose_name='Endereço / Bairro'),
        ),
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço / Logradouro'),
        ),
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço / Número'),
        ),
    ]
