# Generated by Django 3.0.7 on 2020-07-01 14:24

from django.db import migrations
from django.db.models import F


def zera_localizasus(apps, schema_editor):
    Notificacao = apps.get_model('notificacoes', 'Notificacao')
    Notificacao.objects.update(
        estabelecimento_saude_referencia=None,
        coordenadas_atualizadas_em=None,
    )

    Notificacao.objects.filter(latitude__isnull=False, latitude__lte=-30).update(
        latitude=F('longitude'),
        longitude=F('latitude'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0036_auto_20200630_2134'),
    ]

    operations = [
        migrations.RunPython(zera_localizasus),
    ]
