# Generated by Django 3.0.7 on 2020-07-01 22:09

from django.db import migrations

from notificacoes.models import PacienteInternacao


def zerar_paciente_interacoes(a, b):
    PacienteInternacao.objects.all().delete()
    PacienteInternacao.processar_dados_censo_leitos_imd()

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0037_auto_20200701_1124'),
    ]

    operations = [
        migrations.RunPython(zerar_paciente_interacoes)
    ]
