# Generated by Django 3.0.7 on 2020-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0038_auto_20200701_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='endereco_logradouro',
            field=models.CharField(max_length=255, verbose_name='Endereço / Logradouro'),
        ),
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='endereco_numero',
            field=models.CharField(max_length=255, verbose_name='Endereço / Número'),
        ),
        migrations.AlterField(
            model_name='pacienteinternacao',
            name='sexo',
            field=models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1),
        ),
    ]
