# Generated by Django 3.0.7 on 2020-07-06 18:13

from django.db import migrations
from django.db.models import F


def corrigir_dados_obitos(apps, schema_editor):
    Notificacao = apps.get_model('notificacoes', 'Notificacao')
    PacienteInternacao = apps.get_model('notificacoes', 'PacienteInternacao')

    qs = Notificacao.objects.filter(data=F('paciente_internado__data_do_obito'))
    ids_pacientes = qs.values_list('paciente_internado', flat=True)
    PacienteInternacao.objects.filter(id__in=ids_pacientes).update(data_do_obito=None,
                                                                   sexo='',
                                                                   idade=None,
                                                                   endereco_logradouro='',
                                                                   endereco_numero='',
                                                                   endereco_bairro=None
    )
    qs.update(paciente_internado=None)


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0039_auto_20200702_0802'),
    ]

    operations = [
        migrations.RunPython(corrigir_dados_obitos)
    ]
