# Generated by Django 3.0.7 on 2020-07-06 17:28

from django.db import migrations, models


def seta_resultado_teste_positivo_para_obitos_confirmados(apps, schema_editor):
    PacienteInternacao = apps.get_model("notificacoes", "PacienteInternacao")
    PacienteInternacao.objects.filter(data_do_obito__isnull=False).update(resultado_do_teste_covid_19='Confirmado')


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0040_auto_20200706_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinternacao',
            name='resultado_do_teste_covid_19',
            field=models.CharField(blank=True, choices=[('Confirmado', 'Confirmado'), ('Descartado', 'Descartado'), ('Suspeito', 'Suspeito')], max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(seta_resultado_teste_positivo_para_obitos_confirmados),
    ]
