# Generated by Django 3.0.7 on 2020-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0041_pacienteinternacao_resultado_do_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinternacao',
            name='local_de_trabalho',
            field=models.CharField(default='', max_length=255, verbose_name='Local de Trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacienteinternacao',
            name='ocupacao',
            field=models.CharField(default='', max_length=255, verbose_name='Ocupação'),
            preserve_default=False,
        ),
    ]
