# Generated by Django 3.0.7 on 2020-07-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0042_auto_20200707_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteinternacao',
            name='local_de_trabalho',
        ),
        migrations.RemoveField(
            model_name='pacienteinternacao',
            name='ocupacao',
        ),
    ]
