# Generated by Django 3.0.7 on 2020-07-08 14:45
import os
from django.conf import settings

from django.db import migrations

from base.management.commands.processar_arquivos_auxiliares import processar_municipios
from notificacoes.management.commands.processar_notificacoes import Command

def corrigir_dados_bairros(apps, schema_editor):
    path_dir_fixtures = os.path.join(settings.BASE_DIR, 'base/fixtures')

    filename = os.path.join(path_dir_fixtures, 'municipios.csv')
    filename_populacao = os.path.join(path_dir_fixtures, 'municipios_populacao.csv')
    processar_municipios(filename, filename_populacao)

    AssociacaoBairro = apps.get_model("base", "AssociacaoBairro")
    AssociacaoBairro.objects.filter(nome__iexact='potengi', bairro__nome='OUTRO').delete()
    AssociacaoBairro.objects.filter(nome__iexact='SANTO ANTÔNIO', bairro__nome='OUTRO').delete()
    AssociacaoBairro.objects.filter(nome__iexact='BELA VISTA', bairro__nome='OUTRO').delete()

    reprocessar_notificacoes = Command()
    reprocessar_notificacoes.handle()

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0044_auto_20200708_1145'),
    ]

    operations = [
        migrations.RunPython(corrigir_dados_bairros)
    ]
