# Generated by Django 3.0.7 on 2020-07-08 17:49

from django.db import migrations

from notificacoes.models import TipoNotificacaoMotivoCancelamento


def seta_motivo_cancelamento_notificacao(apps, schema_editor):
    Notificacao = apps.get_model("notificacoes", "Notificacao")

    qs = Notificacao.objects.exclude(dados_esusve__municipio_de_residencia__iexact='Natal')
    qs.update(tipo_motivo_desativacao=TipoNotificacaoMotivoCancelamento.MUNICIPIO_RESIDENCIA_EXTERNO)


    qs = Notificacao.objects.filter(notificacao_principal__isnull=False)
    qs.update(tipo_motivo_desativacao=TipoNotificacaoMotivoCancelamento.NOTIFICACAO_SIMILAR)


    qs = Notificacao.objects.filter(ativa=False, tipo_motivo_desativacao__isnull=True)
    qs.update(tipo_motivo_desativacao=TipoNotificacaoMotivoCancelamento.BAIRRO_OUTROS)

    # print((Notificacao.objects.filter(ativa=False).count(),
    #        Notificacao.objects.filter(tipo_motivo_desativacao__isnull=False).count()))


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0045_auto_20200708_1145'),
    ]

    operations = [
        migrations.RunPython(seta_motivo_cancelamento_notificacao)
    ]
