# Generated by Django 3.0.7 on 2020-07-08 23:36

from django.db import migrations

def setar_ativa_false(apps, schema_editor):
    Notificacao = apps.get_model("notificacoes", "Notificacao")
    Notificacao.objects.filter(tipo_motivo_desativacao__isnull=False, ativa=True).update(ativa=False)

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0046_auto_20200708_1449'),
    ]

    operations = [
        migrations.RunPython(setar_ativa_false)
    ]
