# Generated by Django 3.0.7 on 2020-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0048_auto_20200708_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_motivo_desativacao',
            field=models.PositiveIntegerField(choices=[[1, 'Município de residência externo'], [2, 'Evolução do caso igual a cancelado'], [3, 'motivo desconhecido'], [4, 'Nome completo vazio'], [4, 'Notificação repetida'], [5, 'Notificação similar'], [6, 'Bairro outros']], null=True),
        ),
    ]
