# Generated by Django 3.0.7 on 2020-07-14 02:23

from django.db import migrations

from base.utils import to_date


def ajustes_chaves_json_dados_esusve(apps, schema_editor):
    Notificacao = apps.get_model("notificacoes", "Notificacao")

    for numero, dados_esusve in Notificacao.objects.filter(dados_esusve__has_key='gestante').values_list('numero',
                                                                                                         'dados_esusve'):
        dados_esusve['gestante_de_alto_risco'] = dados_esusve.pop('gestante')
        Notificacao.objects.filter(numero=numero).update(dados_esusve=dados_esusve)

    for numero, dados_esusve in Notificacao.objects.filter(dados_esusve__has_key='data_de_coleta_do_teste').values_list(
            'numero', 'dados_esusve'):
        dados_esusve['data_da_coleta_do_teste'] = dados_esusve.pop('data_de_coleta_do_teste')
        Notificacao.objects.filter(numero=numero).update(dados_esusve=dados_esusve)

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0051_historiconotificacaoatualizacao'),
    ]

    operations = [
        migrations.RunPython(ajustes_chaves_json_dados_esusve)
    ]
