# Generated by Django 3.0.7 on 2020-07-14 09:01
import datetime
from django.db import migrations

def seta_datas(apps, schema_editor):
    Notificacao = apps.get_model("notificacoes", "Notificacao")
    Notificacao.objects.filter(numero='202089760').update(data=datetime.datetime(2020, 3, 11))
    Notificacao.objects.filter(numero='202089822').update(data=datetime.datetime(2020, 3, 14))



class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0052_auto_20200713_2323'),
    ]

    operations = [
        migrations.RunPython(seta_datas)
    ]
