# Generated by Django 3.0.7 on 2020-07-16 01:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.db.utils import IntegrityError
import datetime

def migra_dados_alterados(apps, schema_editor):
    HistoricoNotificacaoAtualizacao = apps.get_model("notificacoes", "HistoricoNotificacaoAtualizacao")
    for h in HistoricoNotificacaoAtualizacao.objects.all():
        dados_esusve_alterado = h.dados_esusve_alterado
        dados_alterado = {'dados_esusve': dados_esusve_alterado}
        try:
            HistoricoNotificacaoAtualizacao.objects.filter(id=h.id).update(dados_alterado=dados_alterado,
                                                                           data=h.dados_esusve_atualizados_em)
        except IntegrityError:
            HistoricoNotificacaoAtualizacao.objects.filter(id=h.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0053_auto_20200714_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotificacaoatualizacao',
            name='dados_alterado',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historiconotificacaoatualizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16)),
            preserve_default=False,
        ),
        migrations.RunPython(migra_dados_alterados)
    ]
