# Generated by Django 3.0.7 on 2020-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0055_auto_20200715_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='numero',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='número da notificação'),
        ),
    ]
