# Generated by Django 3.0.7 on 2020-07-20 15:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0057_auto_20200716_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimportacao',
            name='dados_do_processamento',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
