# Generated by Django 3.0.7 on 2020-07-20 19:07

from django.db import migrations
from base.caches import ControleCache

def zerar_staus_cache_notificacoes(apps, schema_editor):
    ControleCache.processamento_notificacoes().reset()


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0058_uploadimportacao_dados_do_processamento'),
    ]

    operations = [
        migrations.RunPython(zerar_staus_cache_notificacoes)
    ]
