# Generated by Django 3.0.7 on 2020-07-21 02:12

from django.db import migrations

from base.caches import ControleCache
from notificacoes.models import TipoNotificacaoMotivoCancelamento


def reprocessar_5_ultimos_csvs(apps, schema_editor):
    Notificacao = apps.get_model("notificacoes", "Notificacao")
    UploadImportacao = apps.get_model("notificacoes", "UploadImportacao")

    UploadImportacao.objects.filter(id__gte=63).update(processado=False)

    Notificacao.objects.filter(dados_esusve__nome_completo=None).update(ativa=False,
                                                                       tipo_motivo_desativacao=TipoNotificacaoMotivoCancelamento.NOME_COMPLETO_VAZIO)

    ControleCache.processamento_notificacoes().reset()


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0059_auto_20200720_1607'),
    ]

    operations = [
        migrations.RunPython(reprocessar_5_ultimos_csvs)
    ]
