# Generated by Django 3.0.7 on 2020-08-10 21:46

from django.db import migrations

def atualizar_dados(apps, schema_editor):
    PacienteInternacao = apps.get_model("notificacoes", "PacienteInternacao")
    municipio_map = dict(PacienteInternacao.objects.values_list('dados_censo_leitos__paciente_municipio_codigo',
                                           'dados_censo_leitos__paciente_municipio_nome').distinct())



    for dados in PacienteInternacao.objects.values('pk', 'dados_censo_leitos'):
        municipio_codigo = dados['dados_censo_leitos']['paciente_municipio_codigo']
        dados['dados_censo_leitos']['paciente_municipio_nome'] = dados['dados_censo_leitos'].get('paciente_municipio_nome', municipio_map[municipio_codigo])
        PacienteInternacao.objects.filter(pk=dados['pk']).update(dados_censo_leitos=dados['dados_censo_leitos'])


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0062_auto_20200810_1509'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados)
    ]
