# Generated by Django 3.0.7 on 2020-07-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0061_auto_20200803_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='data_da_coleta_do_teste',
            field=models.DateField(null=True, verbose_name='Data da coleta do teste'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_de_nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_do_inicio_dos_sintomas',
            field=models.DateField(null=True, verbose_name='Data do início dos sintomas'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_incidencia',
            field=models.DateField(null=True, verbose_name='Data de incidência'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_motivo_desativacao',
            field=models.PositiveIntegerField(choices=[[1, 'Município de residência externo'], [2, 'Evolução do caso igual a cancelado'], [3, 'motivo desconhecido'], [8, 'Nome completo vazio'], [4, 'Notificação repetida'], [5, 'Notificação similar'], [6, 'Bairro outros'], [7, 'Associações de bairro pertecente a outros, mas localidade obtida do CEP pertence a cidade']], null=True),
        ),
    ]
