# Generated by Django 3.0.7 on 2020-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0062_auto_20200810_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinternacao',
            name='cns',
            field=models.CharField(default='', max_length=255, verbose_name='CNS ou CPF'),
            preserve_default=False,
        ),
    ]
