# Generated by Django 3.0.7 on 2020-08-13 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacoes', '0063_pacienteinternacao_cns'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimportacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[0, 'CSV'], [1, 'JSON']], default=0),
        ),
        migrations.AlterField(
            model_name='uploadimportacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
