# Generated by Django 3.0.7 on 2020-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0064_auto_20200813_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimportacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[0, 'ESUS-VE NOTIFICA CSV'], [1, 'ESUS-VE NOTIFICA API']], default=0),
        ),
    ]
