# Generated by Django 3.0.7 on 2020-08-21 18:44

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20200821_1017'),
        ('notificacoes', '0065_auto_20200821_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoSivepGripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número da notificação')),
                ('dados_sivepgripe', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hash_dados_sivepgripe', models.CharField(db_index=True, max_length=56, verbose_name='Hash dados Sivep Gripe')),
                ('data', models.DateField(null=True, verbose_name='Data da Notificação')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadimportacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[0, 'ESUS-VE NOTIFICA CSV'], [1, 'ESUS-VE NOTIFICA API'], [2, 'SIVEP GRIPE DBF'], [3, 'SIVEP GRIPE API']], default=0),
        ),
        migrations.CreateModel(
            name='Obito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_declaracao_obito', models.CharField(blank=True, max_length=30, verbose_name='Número da Declaração de Óbito')),
                ('data_do_obito', models.DateField(verbose_name='Data do óbito')),
                ('resultado_do_teste_covid_19', models.CharField(blank=True, choices=[('Confirmado', 'Confirmado'), ('Descartado', 'Descartado'), ('Suspeito', 'Suspeito')], max_length=255, verbose_name='Resultado do Teste - COVID-19')),
                ('confirmado_covid19', models.NullBooleanField(default=None)),
                ('arquivo_declaracao_obito', models.FileField(blank=True, max_length=255, null=True, upload_to='obito/declaracoes_obito', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Declaração de Óbito')),
                ('arquivo_resultado_exame_covid19', models.FileField(blank=True, max_length=255, null=True, upload_to='obito/resultados_exame_covid19', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Resultado do Exame - COVID19')),
                ('local_do_obito', models.ForeignKey(blank=True, help_text='Caso o óbito tenha ocorrido no domicílio, deixe vazio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EstabelecimentoSaude', verbose_name='Local do Óbito')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.PessoaFisica', unique=True)),
            ],
        ),
    ]
