# Generated by Django 3.0.7 on 2020-08-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0065_auto_20200821_1544'),
    ]

    operations = [
    ]
