# Generated by Django 3.0.7 on 2020-08-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0066_auto_20200821_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obito',
            options={'permissions': [('pode_registrar_obito', 'Pode Registrar Óbito'), ('pode_validar_obito', 'Pode Validar Óbito')], 'verbose_name': 'Óbito', 'verbose_name_plural': 'Óbitos'},
        ),
    ]
