# Generated by Django 3.0.7 on 2020-08-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0067_auto_20200822_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-data_de_investigacao'], 'permissions': [('pode_encerrar_monitoramento', 'Pode encerrar monitoramento')], 'verbose_name': 'Monitoramento', 'verbose_name_plural': 'Monitoramentos'},
        ),
    ]
