# Generated by Django 3.0.7 on 2020-08-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0065_auto_20200821_1456'),
        ('notificacoes', '0068_auto_20200822_1142'),
    ]

    operations = [
    ]
