# Generated by Django 3.0.7 on 2020-08-24 15:25

from django.db import migrations

from notificacoes.management.commands.migracao_pessoa_fisica import atualizar_endereco


def atualizar_endereco_pessoa_fisica(apps, schema_editor):
    atualizar_endereco()

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0070_auto_20200824_0928'),
    ]

    operations = [
        migrations.RunPython(atualizar_endereco_pessoa_fisica)
    ]
