# Generated by Django 3.0.7 on 2020-08-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20200824_1424'),
        ('notificacoes', '0073_auto_20200824_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaosivepgripe',
            name='id',
        ),
        migrations.AlterField(
            model_name='notificacaosivepgripe',
            name='numero',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='número da notificação'),
        ),
        migrations.AddField(
            model_name='obito',
            name='notificacao_sivep_gripe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='notificacoes.NotificacaoSivepGripe'),
        ),
        migrations.AlterField(
            model_name='obito',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.PessoaFisica'),
        ),
        migrations.AlterField(
            model_name='obito',
            name='resultado_do_teste_covid_19',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('Descartado', 'Descartado'), ('Suspeito', 'Suspeito')], max_length=255, verbose_name='Resultado do Teste - COVID-19'),
        ),
    ]
