# Generated by Django 3.0.7 on 2020-08-27 12:31
from django.core.management import call_command
from django.db import migrations


def importar_dados_paciente_internado_com_obito(apps, schema_editor):
    call_command('migracao_dados_obitos')


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0074_auto_20200825_1729'),
    ]

    operations = [
        #migrations.RunPython(importar_dados_paciente_internado_com_obito)
    ]
