# Generated by Django 3.0.7 on 2020-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0075_auto_20200827_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='dados_esusve',
            new_name='dados',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='dados_esusve_alterado',
            new_name='dados_alterado',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='dados_esusve_atualizados_em',
            new_name='dados_atualizados_em',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='hash_dados_esusve',
            new_name='hash_dados',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='fonte_dados',
            field=models.PositiveIntegerField(choices=[[0, 'ESUS-VE NOTIFICA'], [1, 'SIVEP GRIPE']], default=0),
        ),
    ]
