# Generated by Django 3.0.7 on 2020-09-01 13:13

from django.db import migrations, models


def gerar_ids(apps, schema_editor):
    Notificacao = apps.get_model('notificacoes', 'Notificacao')
    for id, notificacao in enumerate(Notificacao.objects.all()):
        notificacao.id = id + 1
        notificacao.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0076_auto_20200901_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(gerar_ids)
    ]
