# Generated by Django 3.0.7 on 2020-09-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0078_auto_20200901_1021'),
    ]

    operations = [
        # Remove pk
        migrations.AlterField(
            model_name='notificacao',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número da notificação'),
        ),

        #Define pk
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        #Recria foreign key constraints
        migrations.AlterField(
            model_name='historiconotificacaoassociacaobairrooutros',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.Notificacao'),
        ),
        migrations.AlterField(
            model_name='historiconotificacaoatualizacao',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.Notificacao'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacoes.Notificacao', verbose_name='Notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='notificacao_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.Notificacao'),
        ),
    ]
