# Generated by Django 3.0.7 on 2020-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0079_auto_20200901_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
