# Generated by Django 3.0.10 on 2020-09-03 19:09

from django.db import migrations

from notificacoes.models import TipoMotivoEncerramento


def criar_obitos_das_notificacoes_encerradas_por_obito(apps, schema_editor):
    Notificacao = apps.get_model('notificacoes', 'Notificacao')
    Obito = apps.get_model('notificacoes', 'Obito')
    for notificacao in Notificacao.objects.filter(encerrada_motivo=TipoMotivoEncerramento.OBITO):
        if not Obito.objects.filter(pessoa=notificacao.pessoa).exists():
            Obito.objects.create(
                pessoa=notificacao.pessoa,
                bairro=notificacao.bairro,
                data_do_obito=notificacao.data_do_encerramento,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0080_auto_20200901_1400'),
    ]

    operations = [
        migrations.RunPython(criar_obitos_das_notificacoes_encerradas_por_obito),
    ]
