# Generated by Django 3.0.7 on 2020-09-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0081_auto_20200903_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obito',
            name='notificacao_sivep_gripe',
        ),
        migrations.AddField(
            model_name='obito',
            name='notificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.Notificacao'),
        ),
    ]
