# Generated by Django 3.0.7 on 2020-09-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0082_auto_20200904_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacaoSivepGripe',
        ),
    ]
